# Generated by Django 3.2.6 on 2022-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('foodtype', models.TextField()),
                ('qualification', models.FloatField(blank=True, null=True)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
    ]
