# Generated by Django 3.2.6 on 2022-02-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20220201_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='visited',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
