# Generated by Django 3.2.6 on 2022-02-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='visited',
            field=models.TextField(blank=True, null=True),
        ),
    ]
